---
title: "Analysis_JS"
output: pdf_document
date: "2024-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(dplyr)
require(caret)
require(glmnet)
```


```{r}
disclosure <- read.csv('..//data//disclosure_data.csv')
congress <- read.csv('..//data//Congressional_Makeup_117.csv')
```

```{r}
number_of_trades = rep(0, 430)
for (i in 1:430) {
  number_of_trades[i] = sum(congress$fullname[i] == disclosure$representative)
}
```

```{r}
congress <- cbind(congress, number_of_trades)
```

```{r}
congress %>% 
  filter(party == 'Republican') %>%
  select(number_of_trades) %>%
  sum()

congress %>% 
  filter(party == 'Democratic') %>%
  select(number_of_trades) %>%
  sum()
```

```{r}
congress[,c(3,32)] %>% 
  sort_by(number_of_trades, decreasing=TRUE) %>%
  head()
```


```{r}
congress$party <- ifelse(congress$party == 'Democratic', 1, 0)
```

```{r}
congress %>%
  filter(number_of_trades>0) %>%
  select(4,6, 12:31) %>%
  as.matrix() ->
  X

congress %>%
  filter(number_of_trades>0) %>%
  select(32) %>%
  as.matrix() ->
  Y
```

```{r}
lassoOut = cv.glmnet(X ,Y, alpha=1, standardize = FALSE) #Consider why we wouldn't standardize
betaHatLasso = coef(lassoOut,s='lambda.min')
Slasso = which(abs(betaHatLasso) > 1e-16)
```


```{r}
require(corrplot)
disclosure %>%
  group_by(industry) %>%
  summarise(total_count = n()) ->
  s
```

```{r}
arrange(s, desc(total_count))
```
```{r}
disclosure %>%
  group_by(ticker) %>%
  summarise(total_count = n()) ->
  s
```

```{r}
arrange(s, desc(total_count))
```

```{r}
quiver <- read.csv('..//data//quiverquant_congress_trading_all.csv')
```

```{r}
quiver$Traded <- as.Date(quiver$Traded)
```


```{r}
quiver %>%
  group_by(Ticker) %>%
  summarise(total_count = n()) ->
  s
arrange(s, desc(total_count))
```

```{r}
quiver %>%
  filter(Traded < as.Date('2020-01-01')) %>%
  group_by(Ticker) %>%
  summarise(total_count = n()) ->
  s
arrange(s, desc(total_count))
```

```{r}
quiver %>%
  filter(Ticker == 'NVDA') %>%
  filter(Traded < as.Date('2022-01-01')) %>%
  select(Ticker, Name, Trade_Size_USD, Traded, Transaction)
```


```{r}
quiver %>%
  group_by(Name) %>%
  summarise(total_count = n()) ->
  s
arrange(s, desc(total_count))
```
```{r}
sum(s$total_count>10)
```
```{r}
length(unique(s$Name))
```
```{r}
voteview <- read.csv('..//data//voteview_member_ideology.csv')
```


```{r}
legislators_current <- read.csv('..//data//legislators-current.csv')
legislators_historical <- read.csv('..//data//legislators-historical.csv')
```

